Jdp231201 1
piotr-grosicki/project-jdp-2312-01 pull request #1
Opened 2023-11-25 19:24 UTC by AdamP1983PL

2023-11-25 19:50 UTC, piotr-grosicki requested changes

2023-11-25 19:50 UTC, piotr-grosicki commented on .gitignore
> +/src/main/java/com/kodilla/ecommercee/basket/
a czemu to jest w ignore?:)

2023-11-25 19:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/model/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, Long> {
to nie powinno powstac w tym zadaniu

2023-11-25 19:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +public interface ProductService {
to nie powinno powstac w tym zadaniu

2023-11-25 19:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/ProductServiceImpl.java
> +public class ProductServiceImpl implements com.kodilla.ecommercee.service.ProductService {
to nie powinno powstac w tym zadaniu

2023-11-25 19:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/mapper/ProductMapper.java
> +public class ProductMapper {
to nie powinno powstac w tym zadaniu

2023-11-25 19:50 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +server.port=8081
czemu taka zmiana?

2023-11-25 19:50 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +spring.datasource.password=Volvo01Xbox1!
tego hasla nie mozna zmieniac, nikomu poza toba nie bedzie dzialalo. musisz zalozyc baze na tym uzytkowniku co wyzej

2023-11-26 10:35 UTC, AdamP1983PL commented on .gitignore
> +/src/main/java/com/kodilla/ecommercee/basket/
bo u mnie folder basket to "śmietnik" w którym przechowuję fragmentu kodu do wykorzystania w przyszłości... a w praktyce do usunięcia w przyszłości,

2023-11-26 10:37 UTC, AdamP1983PL commented on src/main/resources/application.properties
> +server.port=8081
a bo u mnie 8080 mam zajęty

2023-11-26 10:39 UTC, AdamP1983PL commented on src/main/resources/application.properties
> +server.port=8081
w poprzednich projektach miałem błędy podczas kompilacji przy MySQL5Dialect, w nowych projektach z przyzwyczajenia ustawiam na 8, poprawię to

2023-11-26 11:02 UTC, piotr-grosicki commented on .gitignore
> +/src/main/java/com/kodilla/ecommercee/basket/
no ale nie pracujesz juz samochodzielnie :) projekt jest wspolny, nie moga byc w ignore jakies losowe foldery

2023-11-26 11:03 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +server.port=8081
musi byc 8080, nie pracujesz sam nad projektem

2023-11-26 20:03 UTC, AdamP1983PL commented on src/main/java/com/kodilla/ecommercee/model/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, Long> {
ok, usunięte

2023-11-26 20:05 UTC, AdamP1983PL commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +public interface ProductService {
ok, usunięte

2023-11-26 21:43 UTC, piotr-grosicki requested changes
bez zmian na branchy jak cos :)

2023-11-27 07:13 UTC, piotr-grosicki requested changes

2023-11-27 07:13 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
tego nie powinniscie uzywac, nie jest wam potrzebny bean overriding

2023-11-27 07:13 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/model/entity/Product.java
> +public class Product {
to nie powinno tu powstac

2023-11-27 07:59 UTC, piotr-grosicki requested changes

2023-11-27 07:59 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/model/entity/Product.java
> +public class Product {
Wciaz nie powinno tego byc. Encja jest niepotrzebna zeby zrealizowac pierwsze zadania

2023-11-27 08:51 UTC, piotr-grosicki approved these changes

2023-11-27 08:51 UTC, merged